import { useState } from "react";
import { cn } from "@/lib/utils";
import { Bot, User, FileText, Globe, Volume2, Square, Share2, Download, Copy, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";

export type SourceType = "document" | "web";

export interface Source {
  name: string;
  type: SourceType;
  url?: string;
}

export interface Message {
  id: string;
  role: "user" | "assistant";
  content: string;
  sources?: Source[];
  sourceLabel?: string;
  timestamp: Date;
}

interface ChatMessageProps {
  message: Message;
  isLatest?: boolean;
  currentLanguage?: string;
}

export function ChatMessage({ message, isLatest, currentLanguage = 'english' }: ChatMessageProps) {
  const isUser = message.role === "user";
  const { toast } = useToast();
  const [isSpeaking, setIsSpeaking] = useState(false);
  const [isCopied, setIsCopied] = useState(false);

  // Text-to-Speech
  const handleSpeak = () => {
    if (isSpeaking) {
      window.speechSynthesis.cancel();
      setIsSpeaking(false);
    } else {
      const utterance = new SpeechSynthesisUtterance(message.content);

      // Explicitly set language for better voice selection
      if (currentLanguage === 'tamil') {
        utterance.lang = 'ta-IN';
      } else if (currentLanguage === 'hindi') {
        utterance.lang = 'hi-IN';
      } else {
        utterance.lang = 'en-US';
      }

      utterance.onend = () => setIsSpeaking(false);
      window.speechSynthesis.speak(utterance);
      setIsSpeaking(true);
    }
  };

  // WhatsApp Share
  const handleShare = () => {
    const text = `*Scheme Savvy Answer:*\n\n${message.content}\n\n_Generated by Scheme Savvy AI_`;
    window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, '_blank');
  };

  // Download as Text
  const handleDownload = () => {
    const element = document.createElement("a");
    const file = new Blob([message.content], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = "scheme-details.txt";
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
    toast({ description: "Downloaded successfully!" });
  };

  // Copy to Clipboard
  const handleCopy = async () => {
    await navigator.clipboard.writeText(message.content);
    setIsCopied(true);
    setTimeout(() => setIsCopied(false), 2000);
    toast({ description: "Copied to clipboard!" });
  };

  return (
    <div
      className={cn(
        "flex gap-3 animate-slide-up group",
        isUser ? "flex-row-reverse" : "flex-row"
      )}
      style={{ animationDelay: isLatest ? "0ms" : "0ms" }}
    >
      {/* Avatar */}
      <div
        className={cn(
          "flex-shrink-0 w-9 h-9 rounded-full flex items-center justify-center shadow-soft",
          isUser
            ? "bg-primary text-primary-foreground"
            : "bg-accent text-accent-foreground"
        )}
      >
        {isUser ? <User className="w-4 h-4" /> : <Bot className="w-4 h-4" />}
      </div>

      {/* Message Content */}
      <div className="flex flex-col gap-1 max-w-[85%]">
        <div
          className={cn(
            "px-4 py-3 shadow-soft relative",
            isUser ? "chat-bubble-user" : "chat-bubble-assistant"
          )}
        >
          {/* Source Label */}
          {message.sourceLabel && !isUser && (
            <div className="mb-2 pb-2 border-b border-border/30">
              <span className="inline-flex items-center gap-1.5 px-2 py-0.5 bg-muted/50 rounded text-[10px] font-medium text-muted-foreground uppercase tracking-wide">
                {message.sourceLabel.includes("web") ? (
                  <Globe className="w-3 h-3" />
                ) : (
                  <FileText className="w-3 h-3" />
                )}
                {message.sourceLabel}
              </span>
            </div>
          )}

          <p className="text-sm leading-relaxed whitespace-pre-wrap">
            {message.content}
          </p>

          {/* Source Citations */}
          {message.sources && message.sources.length > 0 && (
            <div className="mt-3 pt-3 border-t border-border/30">
              <p className="text-xs text-muted-foreground mb-2 font-medium">
                Sources:
              </p>
              <div className="flex flex-wrap gap-2">
                {message.sources.map((source, index) => (
                  <span
                    key={index}
                    className={cn(
                      "inline-flex items-center gap-1 px-2 py-1 rounded-md text-xs",
                      source.type === "web"
                        ? "bg-accent/20 text-accent-foreground"
                        : "bg-muted/50 text-muted-foreground"
                    )}
                  >
                    {source.type === "web" ? (
                      <Globe className="w-3 h-3" />
                    ) : (
                      <FileText className="w-3 h-3" />
                    )}
                    {source.url ? (
                      <a
                        href={source.url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="hover:underline"
                      >
                        {source.name}
                      </a>
                    ) : (
                      source.name
                    )}
                  </span>
                ))}
              </div>
            </div>
          )}

          <p
            className={cn(
              "text-[10px] mt-2 opacity-60",
              isUser ? "text-right" : "text-left"
            )}
          >
            {message.timestamp.toLocaleTimeString([], {
              hour: "2-digit",
              minute: "2-digit",
            })}
          </p>
        </div>

        {/* Action Bar (Assistant Only) */}
        {!isUser && (
          <div className="flex items-center gap-1 px-1 opacity-0 group-hover:opacity-100 transition-opacity duration-200">
            <Button variant="ghost" size="icon" className="h-7 w-7 text-muted-foreground hover:text-foreground" onClick={handleSpeak} title="Read Aloud">
              {isSpeaking ? <Square className="w-3.5 h-3.5 fill-current" /> : <Volume2 className="w-3.5 h-3.5" />}
            </Button>
            <Button variant="ghost" size="icon" className="h-7 w-7 text-muted-foreground hover:text-foreground" onClick={handleCopy} title="Copy">
              {isCopied ? <Check className="w-3.5 h-3.5 text-green-500" /> : <Copy className="w-3.5 h-3.5" />}
            </Button>
            <Button variant="ghost" size="icon" className="h-7 w-7 text-muted-foreground hover:text-foreground" onClick={handleShare} title="Share on WhatsApp">
              <Share2 className="w-3.5 h-3.5" />
            </Button>
            <Button variant="ghost" size="icon" className="h-7 w-7 text-muted-foreground hover:text-foreground" onClick={handleDownload} title="Download Text">
              <Download className="w-3.5 h-3.5" />
            </Button>
          </div>
        )}
      </div>
    </div>
  );
}